### ISSUE TITLE
Fails to build on android

### ISSUE THREAD

**Issue by optikalefx** [pushbots/phonegap#33]
With using github (https://github.com/pushbots/phonegap) or the official repo (pushbots-cordova-plugin) building for android fails.

cordova v 6.0.0
phonegap v 6.0.1
Mac os 10.11.13
node v 5.9.1

```
:compileArmv7DebugNdk
 UP-TO-DATE


:compileArmv7DebugSources


:transformClassesWithDexForArmv7Debug

UNEXPECTED TOP-LEVEL EXCEPTION:

com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)




 FAILED



FAILURE: 
Build failed with an exception.



* What went wrong:

Execution failed for task ':transformClassesWithDexForArmv7Debug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2


* Try:

Run with 
--stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.



BUILD FAILED

Total time: 36.989 secs

ERROR building one of the platforms: Error code 1 for command: /Applications/MAMP/htdocs/xxx/phonegap/platforms/android/gradlew with args: cdvBuildDebug,-b,/Applications/MAMP/htdocs/xxx/phonegap/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
You may not have the required environment or OS to build this project

Error: Error code 1 for command: /Applications/MAMP/htdocs/xxx/phonegap/platforms/android/gradlew with args: cdvBuildDebug,-b,/Applications/MAMP/htdocs/xxx/phonegap/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

Fatal error: Command failed: phonegap build android 
```

**Comment by optikalefx** [comment]
So, it doesn't fail alone. It only fails when this plugin is also in the mix.  `https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK`  But ONLY when these two are together. It works fine if each is alone

**Comment by John-C2** [comment]
I'm getting a build failure but only when I have:
PushBots (Latest 1.3.6) and Google Maps (Latest 1.3.9) cordova-plugin-googlemaps together.
Phonegap Build cli-5.2.0

From searching around it seems to be related to the android-support module being fetched by the Google Maps plugin combined with pushbots reference to the same thing, in the attached log you will see:
Fetching plugin "cordova-plugin-android-support-v4" via npm
Pushbots references cordova-plugin-android-support-v4 as well in it's plugin.xml file.

I'm not sure which side has the power to resolve this so that manual changes aren't needed for Phonegap build to run successfully.

Build failure log attached
[debug.txt](https://github.com/pushbots/phonegap/files/211430/debug.txt)

UPDATE: This forked version with the Android support references modified built successfully:
`<plugin spec="https://github.com/olliebennett/phonegap" source="git" />`

**Comment by optikalefx** [comment]
this was a different error than mine, see https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/94#issuecomment-208101378 for my soltuion.

**Comment by buddywa** [comment]
Remove the `android-support-v4.jar` in your Android `platforms/android/libs` directory.

**Comment by AbdullahDiaa** [comment]
That should be fixed with latest release.

**Comment by optikalefx** [comment]
Awesome, will test. Thanks!
