### ISSUE TITLE
Pushbots + Phonegap/cordova 

### ISSUE THREAD

**Issue by hafizramli** [pushbots/phonegap#44]
Hi there i need help for anybody got experience handling the pushbots and cordova..I am using pushbots to retrieve the push notification..But i cant solve the problem how can i make deep linking for example,when the notification popup,i i click the notification,it will redirect to the page that i want..i already watch the tutorial from pushbots, but the tutorial use the java android studio..it totally not same with the cordava apache..until now i failed to link the notification to the .html page ..Please Help me :(  
Thanks You
source pushbots : https://www.youtube.com/watch?v=UuHmjLgPmpc

**Comment by planetcrypton** [comment]
Use the `.on("notification:clicked", yourHandler)` handler.
In `yourHandler` you route as you normally would in your app.
Where to route to, could be 'alert-dependent' since you're able to pass any custom data into the payload of the alert.
Here's a simple example (using Ember.JS) and the payload data is `{ "post_item": 8217 }`:

```
    yourHandler(data) {
        // redirect to 'post' item
        if( data && data.post_item ) {
            this.transitionTo('posts.post', data.post_item);
        }
    }
```
