### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by ViaFabula** [pushbots/phonegap#60]
Hello,

We use Pushbots to manage our application notifications, and since september, Apple notifies us that our IOS builds does not enable push notifications.
The work-around is well known : open the XCode project and check the "Enable Push Notifications" box in project settings.

Our issue is that we are migrating to hosted Continuous Integration solution (that manage all the build and publishing process), and thus, it is not possible anymore to open the XCode project and fix the properties.
All Cordova push notifications plugins have faced the same issue, and most of them fixed it (requiring cordova-ios 4.3.0 and plugin fix, such as this one : https://github.com/urbanairship/phonegap-ua-push/issues/136). 

Is it possible for Pushbots to fix it ?

Best regards

**Comment by physox** [comment]
We have the same issue here, but a possible solution is in sight:
You could use a cordova hook, which creates an entitlements-file.

iTunes connect needs this to recognize if the app is running in development or in production mode.

**Comment by birfincankafein** [comment]
Now I faced this issue and I am not able to open Xcode project and set values because Im using JenkinsCI for build. And no, actually this should not be closed. Pushbots plugin should use cordova hooks inside plugin because this issue related with Pushbots Cordova side and solve this problem inside plugin.
