### ISSUE TITLE
PushbotsPlugin.getRegistrationId not working in android

### ISSUE THREAD

**Issue by raphaelmonte** [pushbots/phonegap#61]
Hi, i'm using build.phonegap with

`<preference name="phonegap-version" value="cli-6.3.0"/>`
`<gap:plugin name="pushbots-cordova-plugin" spec="1.4.7" source="npm" />`
`<preference name="android-build-tool" value="gradle"/>`

and code 
`
PushbotsPlugin.initialize(APPLICATION_ID,  {'android': {'sender_id': GOOGLE_SENDER_ID}});
PushbotsPlugin.getRegistrationId((token: string) => {
    console.log(token);
});
`
The device is registered on pushbots website, but in my code I didn't receive token.

I tried with this code too:
`PushbotsPlugin.on("user:ids", (data) => { 
console.log('TOKEN: ' + data.token) ;
}`

on IOS works great, but in android I get "null registration id" console.

**Comment by OUSoonerTaz** [comment]
Is there actually a resolution to this?  I'm still not getting the token for Android and I'm using v 1.6.2 of the pushbots plugin.

Registering a new Android device is working because I can see the profiles and their tokens being added to my user dashboard and it is successfully tracking the "last seen" column.  I really need to get that device token returned.
